### ISSUE TITLE
Not removing InstallSystem.dmg

### ISSUE THREAD

**Issue by kimnzl** [thelamehacker/macOS-toolkit#1]
https://github.com/thelamehacker/macOS-toolkit/blob/2bae19b805a48be64d5051d83a4a1d3022f8f541/toolkit/macOS_Mojave_ISOMaker.sh#L52
This line should be:
rm ~/Desktop/InstallSystem.dmg

**Comment by thelamehacker** [comment]
Thank you. This has been fixed and closed.
