### ISSUE TITLE
Problem with script

### ISSUE THREAD

**Issue by wyredone** [thelamehacker/macOS-toolkit#2]
When I run the macOS_ISO_creator.sh script I run into this:
-e Restoring BaseSystem.dmg...
	Validating target...done
	Validating source...
Could not recognize "/tmp/osx-image.wZH/input_mount/BaseSystem.dmg" as an image file
Could not validate source - Invalid argument
-e Could not mount BaseSystem.dmg.
"disk7" unmounted.
"disk7" ejected.
"disk6" unmounted.
"disk6" ejected.
Wyres-iMac:Desktop wyre$ 

Im attempting to generate an iso for high Sierra. Ive deleted and redownloaded the installer from the App Store. Also I have rebooted the computer and retried as well as ran the option to specify the InstallESD path. and I keep running into this:
Could not recognize "/tmp/osx-image.FAs/input_mount/BaseSystem.dmg" as an image file
Could not validate source - Invalid argument
-e Could not mount BaseSystem.dmg.

Any ideas?

**Comment by lockejan** [comment]
This script is written for mojave. If you want to use it for a different version you have to change the script to the specified version. Just compare the filename-strings in the script with the ones you want to use and change them as needed.

**Comment by thelamehacker** [comment]
@wyredone This script was designed specifically for Mojave installer. You can use the [universal script](https://github.com/thelamehacker/macOS-toolkit/blob/master/toolkit/macOS_ISO_creator.sh) which works for any version between 10.6 to 10.14.
